sudo: required

language: node_js
node_js:
  - "6"

services:
  - docker

before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - cp config.js config.local.js
  - sed -i -e "s/local/$TRAVIS_BUILD_NUMBER/g" config.local.js
  - if [ "$TRAVIS_BRANCH" == 'develop' ]; then export SKILLS_API_URL='https://fy5p532pni.execute-api.us-west-2.amazonaws.com/dev/skills'; fi
  - if [ "$TRAVIS_BRANCH" == 'develop' ]; then export GOALS_API_URL='http://goals-staging.unleash.x-team.com/api/v1/goals.json'; fi
  - if [ "$TRAVIS_BRANCH" == 'develop' ]; then export PROFILES_API_URL='https://txkaf3ohhf.execute-api.us-west-2.amazonaws.com/staging/profiles'; fi
  - if [ "$TRAVIS_BRANCH" == 'develop' ]; then export PATHS_API_URL='http://paths-staging.unleash.x-team.com/api/v1/paths'; fi
  - if [ "$TRAVIS_BRANCH" == 'develop' ]; then export SLACK_BOT_URL='http://bot.unleash.x-team.com'; fi
  - if [ "$TRAVIS_BRANCH" == 'develop' ]; then export APP_NODE_ENV='staging'; fi

install:
  - docker build -t $AWS_ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com/x-team-unleash:$TRAVIS_BUILD_NUMBER .

script:
  - docker run $AWS_ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com/x-team-unleash:$TRAVIS_BUILD_NUMBER npm run test:lint
  - docker run $AWS_ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com/x-team-unleash:$TRAVIS_BUILD_NUMBER npm run test

deploy:
  - provider: script
    script: ./deploy.sh prod
    on:
      branch: master
  - provider: script
    script: ./deploy.sh staging
    on:
      branch: develop
