sudo: required
dist: trusty
group: edge

language: node_js
node_js:
  - "6"

before_install:
  - pip install --user awscli
  - if [ "$TRAVIS_BRANCH" == 'develop' ]; then export SKILLS_API_URL='https://fy5p532pni.execute-api.us-west-2.amazonaws.com/dev/skills'; fi
  - if [ "$TRAVIS_BRANCH" == 'develop' ]; then export GOALS_API_URL='http://goals-staging.unleash.x-team.com/api/v1/goals.json'; fi
  - if [ "$TRAVIS_BRANCH" == 'develop' ]; then export PROFILES_API_URL='https://txkaf3ohhf.execute-api.us-west-2.amazonaws.com/staging/profiles'; fi
  - if [ "$TRAVIS_BRANCH" == 'develop' ]; then export PATHS_API_URL='http://paths-staging.unleash.x-team.com/api/v1/paths'; fi
  - if [ "$TRAVIS_BRANCH" == 'develop' ]; then export SLACK_BOT_URL='http://bot.unleash.x-team.com'; fi

install:
  - cp config.js config.local.js
  - sed -i -e "s/local_app_version/$TRAVIS_BUILD_NUMBER/g" config.local.js
  - sed -i -e "s/firebase_api_key_value/$FIREBASE_API_KEY/g" config.local.js
  - sed -i -e "s/firebase_auth_domain_value/$FIREBASE_AUTH_DOMAIN/g" config.local.js
  - sed -i -e "s,firebase_database_url_value,$FIREBASE_DATABASE_URL,g" config.local.js
  - sed -i -e "s/firebase_storage_bucket_value/$FIREBASE_STORAGE_BUCKET/g" config.local.js
  - sed -i -e "s/firebase_messaging_sender_id_value/$FIREBASE_MESSAGING_SENDER_ID/g" config.local.js
  - sed -i -e "s,https://fy5p532pni.execute-api.us-west-2.amazonaws.com/dev/skills,$SKILLS_API_URL,g" config.local.js
  - sed -i -e "s,http://goals-staging.unleash.x-team.com/api/v1/goals.json,$GOALS_API_URL,g" config.local.js
  - sed -i -e "s,https://txkaf3ohhf.execute-api.us-west-2.amazonaws.com/staging/profiles,$PROFILES_API_URL,g" config.local.js
  - sed -i -e "s,http://paths-staging.unleash.x-team.com/api/v1/paths,$PATHS_API_URL,g" config.local.js
  - sed -i -e "s,slack_bot_url_value,$SLACK_BOT_URL,g" config.local.js
  - yarn

script:
  - npm run test:lint
  - npm run test

after_success:
  - npm run build

deploy:
  - provider: s3
    access_key_id: "$AWS_ACCESS_KEY_ID"
    secret_access_key: "$AWS_SECRET_ACCESS_KEY"
    bucket: "x-team-unleash-app"
    skip_cleanup: true
    local_dir: build
    region: "us-west-2"
    on:
      branch: "deployment_#471"
