sudo: required
language: node_js
services:
  - docker
node_js:
  - '0.10'
before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'
  - 'gem install sass --version "=3.4.8"'
  - 'gem install compass --version "=1.0.1"'
before_deploy:
  - if [ $TRAVIS_TAG ]; then export UNLEASH_ENV='production'; fi
  - if [ $TRAVIS_TAG ]; then export BOT_URL='http://bot.unleash.x-team.com'; fi
  - if [ $TRAVIS_TAG ]; then export PROFILES_URL='https://txkaf3ohhf.execute-api.us-west-2.amazonaws.com/prod/profiles'; fi
  - if [ $TRAVIS_TAG ]; then export SKILLS_URL='http://skills.unleash.x-team.com/api/v1/skills'; fi
  - if [ $TRAVIS_TAG ]; then export GOALS_URL='http://goals.unleash.x-team.com/api/v1/goals'; fi
  - if [ $TRAVIS_TAG ]; then export PATHS_URL='http://paths.unleash.x-team.com/api/v1/paths'; fi
  - if [ $TRAVIS_TAG ]; then export MIXPANEL_ANALYTICS_ENABLED='true'; fi
  - if [ $TRAVIS_TAG ]; then export ZAPIER_WEBHOOK_URL='https://hooks.zapier.com/hooks/catch/576991/tyby3q/'; fi
  - grunt build
deploy:
  - provider: script
    skip_cleanup: true
    script: ./deploy.sh $TRAVIS_TAG
    on:
      tags: true
      all_branches: true
      condition: "$TRAVIS_TAG =~ ^1.*$"
