sudo: required

language: node_js
node_js:
  - "6"

services:
  - docker

before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - cp config.js config.local.js
  - sed -i -e "s/local/$TRAVIS_BUILD_NUMBER/g" config.local.js

install:
  - docker build -t $AWS_ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com/x-team-unleash:$TRAVIS_BUILD_NUMBER .

script:
  - docker run $AWS_ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com/x-team-unleash:$TRAVIS_BUILD_NUMBER npm run test:lint
  - docker run $AWS_ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com/x-team-unleash:$TRAVIS_BUILD_NUMBER npm run test

deploy:
  provider: script
  script: ./deploy.sh
  on:
    branch: master
